var IMAGE_DIR = 'images/',
    GAME_WIDTH = 600,
    GAME_HEIGHT = 600,
    Z_BACKGROUND = 1,
    PLAYER_STEP = 7,
    Z_SHADOWS = 10,
    SCROLL_SPEED = 3,
    NUMBER_OF_OBSTACLES = 3;
    Z_CHARACTERS = 20,
    Z_GUI=99999,
    PAUSED = 1;